ALTER TABLE transactions ADD COLUMN IF NOT EXISTS requeue_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS last_requeued_at TIMESTAMPTZ;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
