ALTER TABLE queues
ADD COLUMN IF NOT EXISTS open_cases INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_cases INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS cases_breached INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS breach_rate DOUBLE PRECISION NOT NULL DEFAULT 0.0;
