package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"time"
	"path/filepath"

	"github.com/Sayantan-dev1003/aegis/api/internal/middleware"
	"github.com/Sayantan-dev1003/aegis/api/internal/model"
	"github.com/Sayantan-dev1003/aegis/api/internal/repository"
	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
)

type RetrainHandler struct {
	retrainRepo *repository.RetrainRepository
	modelRepo   *repository.ModelRepository
}

func NewRetrainHandler(retrainRepo *repository.RetrainRepository, modelRepo *repository.ModelRepository) *RetrainHandler {
	return &RetrainHandler{retrainRepo: retrainRepo, modelRepo: modelRepo}
}

func (h *RetrainHandler) respondError(w http.ResponseWriter, msg string, code int) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	fmt.Fprintf(w, `{"error": "%s"}`, msg)
}

func (h *RetrainHandler) List(w http.ResponseWriter, r *http.Request) {
	jobs, err := h.retrainRepo.List(r.Context())
	if err != nil {
		h.respondError(w, "internal server error", http.StatusInternalServerError)
		return
	}
	if jobs == nil {
		jobs = []model.RetrainJob{}
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(jobs)
}

func (h *RetrainHandler) Trigger(w http.ResponseWriter, r *http.Request) {
	info, ok := r.Context().Value(middleware.AnalystInfoKey).(middleware.AnalystInfo)
	if !ok {
		log.Warn().Msg("AnalystInfo not found in context")
	}
	
	hasPending, err := h.retrainRepo.HasPendingJob(r.Context())
	if err != nil {
		h.respondError(w, "failed to check pending jobs", http.StatusInternalServerError)
		return
	}
	if hasPending {
		h.respondError(w, "a retrain job is already in progress", http.StatusConflict)
		return
	}

	jobID := "job-" + uuid.New().String()[:8]
	job := model.RetrainJob{
		ID:          jobID,
		Status:      "pending",
		TriggeredBy: info.ID,
		StartedAt:   time.Now().UTC(),
	}

	if err := h.retrainRepo.Create(r.Context(), job); err != nil {
		h.respondError(w, "failed to create retrain job", http.StatusInternalServerError)
		return
	}

	// Start background goroutine to execute ML pipeline
	go h.runMLPipeline(jobID)

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusAccepted)
	json.NewEncoder(w).Encode(map[string]string{"message": "Retrain job started", "job_id": jobID})
}

func (h *RetrainHandler) runMLPipeline(jobID string) {
	ctx := context.Background()
	start := time.Now()

	// More robust path resolution using environment variable or fallback to relative path from executable
	mlWorkerDir := os.Getenv("ML_WORKER_DIR")
	if mlWorkerDir == "" {
		// A generic fallback for dev is relative to current working directory
		cwd, err := os.Getwd()
		if err != nil {
			log.Error().Err(err).Msg("Failed to get current working directory for fallback")
			cwd = "."
		}
		mlWorkerDir = filepath.Join(cwd, "..", "ml-worker")
	}
	scriptPath := filepath.Join(mlWorkerDir, "run_pipeline.sh")

	log.Info().Str("job_id", jobID).Msg("Starting ML Pipeline execution")

	cmd := exec.Command("bash", scriptPath)
	cmd.Dir = mlWorkerDir

	// In a real environment, you'd capture stdout/stderr to a log file
	out, err := cmd.CombinedOutput()
	
	durationSec := int(time.Since(start).Seconds())
	
	if err != nil {
		log.Error().Err(err).Str("output", string(out)).Msg("ML Pipeline failed")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	log.Info().Str("job_id", jobID).Msg("ML Pipeline completed successfully")

	// Parse model metadata generated by the python script
	metadataPath := filepath.Join(mlWorkerDir, "artifacts", "model_metadata.json")
	metadataFile, err := os.ReadFile(metadataPath)
	if err != nil {
		log.Error().Err(err).Msg("Failed to read model_metadata.json")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	// Unmarshal to get metrics (we'll extract best_validation_aucpr as f1/pr score for demo)
	var metadata map[string]interface{}
	if err := json.Unmarshal(metadataFile, &metadata); err != nil {
		log.Error().Err(err).Msg("Failed to unmarshal model_metadata.json")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}
	
	// Parse metrics strictly without fallback
	f1Score, ok := metadata["f1_score"].(float64)
	if !ok {
		log.Error().Msg("f1_score missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}
	
	precision, ok := metadata["precision"].(float64)
	if !ok {
		log.Error().Msg("precision missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}
	
	recall, ok := metadata["recall"].(float64)
	if !ok {
		log.Error().Msg("recall missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}
	
	accuracy, ok := metadata["accuracy"].(float64)
	if !ok {
		log.Error().Msg("accuracy missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}
	
	rocAuc, ok := metadata["roc_auc"].(float64)
	if !ok {
		log.Error().Msg("roc_auc missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}
	
	prAuc, ok := metadata["pr_auc"].(float64)
	if !ok {
		log.Error().Msg("pr_auc missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}
	
	// Create a new model version in the database
	newVersion := fmt.Sprintf("v%s", time.Now().Format("20060102.1504"))
	
	err = h.modelRepo.CreateVersion(ctx, 
		"mod-"+uuid.New().String()[:8], 
		newVersion, 
		filepath.Join(mlWorkerDir, "deployment"),
		f1Score, 
		precision, 
		recall,
		accuracy,
		rocAuc,
		prAuc,
	)
	
	if err != nil {
		log.Error().Err(err).Msg("Failed to insert new model version")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	// Mark job as completed
	h.retrainRepo.UpdateStatus(ctx, jobID, "completed", &durationSec)
}
