package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"time"

	"github.com/Sayantan-dev1003/aegis/api/internal/middleware"
	"github.com/Sayantan-dev1003/aegis/api/internal/model"
	"github.com/Sayantan-dev1003/aegis/api/internal/repository"
	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
)

type RetrainHandler struct {
	retrainRepo  *repository.RetrainRepository
	modelRepo    *repository.ModelRepository
	incidentRepo *repository.IncidentRepository
}

func NewRetrainHandler(retrainRepo *repository.RetrainRepository, modelRepo *repository.ModelRepository, incidentRepo *repository.IncidentRepository) *RetrainHandler {
	return &RetrainHandler{
		retrainRepo:  retrainRepo,
		modelRepo:    modelRepo,
		incidentRepo: incidentRepo,
	}
}

func (h *RetrainHandler) respondError(w http.ResponseWriter, msg string, code int) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	fmt.Fprintf(w, `{"error": "%s"}`, msg)
}

func (h *RetrainHandler) List(w http.ResponseWriter, r *http.Request) {
	jobs, err := h.retrainRepo.List(r.Context())
	if err != nil {
		h.respondError(w, "internal server error", http.StatusInternalServerError)
		return
	}
	if jobs == nil {
		jobs = []model.RetrainJob{}
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(jobs)
}

func (h *RetrainHandler) Trigger(w http.ResponseWriter, r *http.Request) {
	info, ok := r.Context().Value(middleware.AnalystInfoKey).(middleware.AnalystInfo)
	if !ok {
		log.Warn().Msg("AnalystInfo not found in context")
	}

	hasPending, err := h.retrainRepo.HasPendingJob(r.Context())
	if err != nil {
		h.respondError(w, "failed to check pending jobs", http.StatusInternalServerError)
		return
	}
	if hasPending {
		h.respondError(w, "a retrain job is already in progress", http.StatusConflict)
		return
	}

	jobID := "job-" + uuid.New().String()[:8]
	job := model.RetrainJob{
		ID:          jobID,
		Status:      "pending",
		TriggeredBy: info.ID,
		StartedAt:   time.Now().UTC(),
	}

	if err := h.retrainRepo.Create(r.Context(), job); err != nil {
		h.respondError(w, "failed to trigger retrain", http.StatusInternalServerError)
		return
	}

	// Start background goroutine to execute ML pipeline
	go h.runMLPipeline(jobID)

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusAccepted)
	json.NewEncoder(w).Encode(map[string]string{"message": "Retrain job started", "job_id": jobID})
}

func (h *RetrainHandler) runMLPipeline(jobID string) {
	ctx := context.Background()
	start := time.Now()

	// More robust path resolution using environment variable or fallback to relative path from executable
	mlWorkerDir := os.Getenv("ML_WORKER_DIR")
	if mlWorkerDir == "" {
		// A generic fallback for dev is relative to current working directory
		cwd, err := os.Getwd()
		if err != nil {
			log.Error().Err(err).Msg("Failed to get current working directory for fallback")
			cwd = "."
		}
		mlWorkerDir = filepath.Join(cwd, "..", "ml-worker")
	}

	mlWorkerURL := os.Getenv("ML_WORKER_URL")
	if mlWorkerURL == "" {
		mlWorkerURL = "http://ml-worker:8000"
	}

	// Make a POST request to trigger retraining
	// Use a client with no timeout, as the ML pipeline can take several minutes
	client := &http.Client{}
	req, err := http.NewRequest("POST", mlWorkerURL+"/retrain", nil)
	if err != nil {
		log.Error().Err(err).Msg("Failed to create HTTP request for ML pipeline")
	}

	var out []byte
	if err == nil {
		resp, reqErr := client.Do(req)
		err = reqErr
		if err == nil {
			defer resp.Body.Close()
			out, _ = io.ReadAll(resp.Body)
			if resp.StatusCode != 200 {
				err = fmt.Errorf("ML Worker returned status %d", resp.StatusCode)
			}
		}
	}

	durationSec := int(time.Since(start).Seconds())

	if err != nil {
		log.Error().Err(err).Str("output", string(out)).Msg("ML Pipeline failed")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)

		// Create an incident
		desc := fmt.Sprintf("Retraining job %s failed. Error: %s\n\nOutput:\n%s", jobID, err.Error(), string(out))
		incident := &model.Incident{
			Title:       "ML Pipeline Failure",
			Description: &desc,
			Status:      "active",
			Severity:    "critical",
		}
		if incErr := h.incidentRepo.Create(ctx, incident); incErr != nil {
			log.Error().Err(incErr).Msg("Failed to create incident for ML pipeline failure")
		}
		return
	}

	log.Info().Str("job_id", jobID).Msg("ML Pipeline completed successfully")

	// Parse model metadata generated by the python script
	metadataPath := filepath.Join(mlWorkerDir, "artifacts", "model_metadata.json")
	metadataFile, err := os.ReadFile(metadataPath)
	if err != nil {
		log.Error().Err(err).Msg("Failed to read model_metadata.json")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	// Unmarshal to get metrics (we'll extract best_validation_aucpr as f1/pr score for demo)
	var metadata map[string]interface{}
	if err := json.Unmarshal(metadataFile, &metadata); err != nil {
		log.Error().Err(err).Msg("Failed to unmarshal model_metadata.json")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	// Parse metrics strictly without fallback
	f1Score, ok := metadata["f1_score"].(float64)
	if !ok {
		log.Error().Msg("f1_score missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	precision, ok := metadata["precision"].(float64)
	if !ok {
		log.Error().Msg("precision missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	recall, ok := metadata["recall"].(float64)
	if !ok {
		log.Error().Msg("recall missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	accuracy, ok := metadata["accuracy"].(float64)
	if !ok {
		log.Error().Msg("accuracy missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	rocAuc, ok := metadata["roc_auc"].(float64)
	if !ok {
		log.Error().Msg("roc_auc missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	prAuc, ok := metadata["pr_auc"].(float64)
	if !ok {
		log.Error().Msg("pr_auc missing from metadata")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	// Read threshold metrics
	thresholdPath := filepath.Join(mlWorkerDir, "reports", "threshold_analysis.json")
	thresholdBytes, err := os.ReadFile(thresholdPath)
	if err != nil {
		log.Warn().Err(err).Msg("Failed to read threshold_analysis.json, continuing with empty metrics")
		thresholdBytes = []byte("[]")
	}

	// Read SHAP metrics
	shapPath := filepath.Join(mlWorkerDir, "reports", "shap_feature_importance.json")
	shapBytes, err := os.ReadFile(shapPath)
	if err != nil {
		log.Warn().Err(err).Msg("Failed to read shap_feature_importance.json, continuing with empty metrics")
		shapBytes = []byte("[]")
	}

	// Create a new model version in the database
	newVersion := fmt.Sprintf("v%s", time.Now().Format("20060102.1504"))

	err = h.modelRepo.CreateVersion(ctx,
		uuid.New().String(),
		newVersion,
		filepath.Join(mlWorkerDir, "deployment"),
		f1Score,
		precision,
		recall,
		accuracy,
		rocAuc,
		prAuc,
		thresholdBytes,
		shapBytes,
	)

	if err != nil {
		log.Error().Err(err).Msg("Failed to insert new model version")
		h.retrainRepo.UpdateStatus(ctx, jobID, "failed", &durationSec)
		return
	}

	// Mark job as completed
	h.retrainRepo.UpdateStatus(ctx, jobID, "completed", &durationSec)
}

// Status returns the current readiness status of the ML Worker
func (h *RetrainHandler) Status(w http.ResponseWriter, r *http.Request) {
	mlWorkerURL := os.Getenv("ML_WORKER_URL")
	if mlWorkerURL == "" {
		mlWorkerURL = "http://ml-worker:8000"
	}

	client := &http.Client{Timeout: 2 * time.Second}
	resp, err := client.Get(mlWorkerURL + "/ready")
	
	status := "offline"
	if err == nil {
		defer resp.Body.Close()
		if resp.StatusCode == 200 {
			status = "live"
		} else if resp.StatusCode == 503 {
			status = "loading"
		}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"status": status})
}
